(executable
 (name main)
 (modules
  ast
  traversal
  fresh_alpha
  builtin
  builtin_relation
  extern_model
  wfs_backend
  identifier
  relation_optimizer
  relation_graph
  translator
  order
  printer
  pipeline
  case_obligation
  main)
 (libraries lang domain util pass diagnostic runtime p4 p4spectec interface unix))
