#!/usr/bin/env python3
"""Catch repeated rule bodies, prefixes and unused failure machinery by size."""
import argparse
from pathlib import Path
import subprocess
import tempfile


def fixture(count):
    clauses = [
        f'def $scan(n) = "unreachable"\n  -- if $fresh_typeId() = "never{i}"'
        for i in range(count)
    ]
    return '\n'.join([
        'syntax typeId = text',
        'builtin dec $fresh_typeId() : typeId',
        'var n : nat',
        'dec $scan(nat) : typeId',
        *clauses,
        'def $scan(n) = $fresh_typeId()',
    ]) + '\n'


def guard_fixture(count):
    guards = [f'  -- if n =/= {i}' for i in range(count)]
    return '\n'.join([
        'syntax typeId = text',
        'builtin dec $fresh_typeId() : typeId',
        'var n : nat',
        'dec $guards(nat) : typeId',
        'def $guards(n) = $fresh_typeId()',
        *guards,
        'def $guards(n) = "fallback"',
    ]) + '\n'


def public_fixture(count):
    return '\n'.join([
        'syntax typeId = text',
        'builtin dec $fresh_typeId() : typeId',
        *(f'dec $f{i}() : typeId\ndef $f{i}() = $fresh_typeId()' for i in range(count)),
    ]) + '\n'


def generated_sizes(exe, make_fixture, counts):
    sizes = []
    with tempfile.TemporaryDirectory() as temp:
        path = Path(temp) / 'size.watsup'
        for count in counts:
            path.write_text(make_fixture(count))
            generated = subprocess.run(
                [str(exe.resolve()), '--fresh-exact-counter', str(path)],
                capture_output=True, check=True
            ).stdout
            assert b'head_property' not in generated, (
                'proof support must eliminate relation membership locally '
                'instead of eagerly emitting every head_property theorem'
            )
            sizes.append(len(generated))
    return sizes


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--exe', required=True, type=Path)
    args = parser.parse_args()
    sizes = generated_sizes(args.exe, fixture, (16, 32, 64))
    # Each added clause has constant work. Doubling must not approach 4x.
    # The absolute ceiling also catches duplicating bulky rules in proof bodies.
    print('generated bytes for 16/32/64 clauses:', *sizes)
    assert sizes[2] <= 2.3 * sizes[1], 'failed-clause expansion is superlinear'
    assert sizes[2] < 320_000, 'unnecessary generated rules or repeated proof bodies'
    sizes = generated_sizes(args.exe, guard_fixture, (16, 32, 64))
    print('generated bytes for 16/32/64 guards:', *sizes)
    assert sizes[2] <= 2.3 * sizes[1], 'failed-guard prefixes expand superlinearly'
    size, = generated_sizes(args.exe, public_fixture, (64,))
    print('generated bytes for 64 straight-line public functions:', size)
    # Includes bounded groups and compatibility aliases. Proof support performs
    # local elimination on demand instead of emitting every head theorem.
    assert size < 250_000, 'unused internal failure machinery is emitted'


if __name__ == '__main__':
    main()
