#!/usr/bin/env python3
"""Catch repeated rule bodies, prefixes and unused failure machinery by size."""
import argparse
from pathlib import Path
import re
import subprocess
import tempfile


def fixture(count):
    clauses = [
        f'def $scan(n) = "unreachable"\n  -- if $fresh_typeId() = "never{i}"'
        for i in range(count)
    ]
    return '\n'.join([
        'syntax typeId = text',
        'builtin dec $fresh_typeId() : typeId',
        'var n : nat',
        'dec $scan(nat) : typeId',
        *clauses,
        'def $scan(n) = $fresh_typeId()',
    ]) + '\n'


def guard_fixture(count):
    guards = [f'  -- if n =/= {i}' for i in range(count)]
    return '\n'.join([
        'syntax typeId = text',
        'builtin dec $fresh_typeId() : typeId',
        'var n : nat',
        'dec $guards(nat) : typeId',
        'def $guards(n) = $fresh_typeId()',
        *guards,
        'def $guards(n) = "fallback"',
    ]) + '\n'


def public_fixture(count):
    return '\n'.join([
        'syntax typeId = text',
        'builtin dec $fresh_typeId() : typeId',
        *(f'dec $f{i}() : typeId\ndef $f{i}() = $fresh_typeId()' for i in range(count)),
    ]) + '\n'


def plan_fixture(count):
    return '\n'.join([
        'syntax typeId = text',
        *(f'dec $f{i}() : typeId\ndef $f{i}() = "value{i}"'
          for i in range(count)),
    ]) + '\n'


def generated_outputs(exe, make_fixture, counts, *, flags=(),
                      reject_head_property=False):
    outputs = []
    with tempfile.TemporaryDirectory() as temp:
        path = Path(temp) / 'size.watsup'
        for count in counts:
            path.write_text(make_fixture(count))
            generated = subprocess.run(
                [str(exe.resolve()), *flags, str(path)],
                capture_output=True, check=True
            ).stdout
            if reject_head_property:
                assert b'head_property' not in generated, (
                    'proof support must eliminate relation membership locally '
                    'instead of eagerly emitting every head_property theorem'
                )
            outputs.append(generated)
    return outputs


def legacy_sizes(exe, make_fixture, counts):
    return [
        len(output)
        for output in generated_outputs(
            exe, make_fixture, counts, flags=('--fresh-exact-counter',),
            reject_head_property=True
        )
    ]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--exe', required=True, type=Path)
    args = parser.parse_args()
    sizes = legacy_sizes(args.exe, fixture, (16, 32, 64))
    # Each added clause has constant work. Doubling must not approach 4x.
    # The absolute ceiling also catches duplicating bulky rules in proof bodies.
    print('generated bytes for 16/32/64 clauses:', *sizes)
    assert sizes[2] <= 2.3 * sizes[1], 'failed-clause expansion is superlinear'
    assert sizes[2] < 240_000, 'unnecessary generated rules or repeated proof bodies'
    sizes = legacy_sizes(args.exe, guard_fixture, (16, 32, 64))
    print('generated bytes for 16/32/64 guards:', *sizes)
    assert sizes[2] <= 2.3 * sizes[1], 'failed-guard prefixes expand superlinearly'
    assert sizes[2] < 120_000, 'failed-guard prefixes repeat proof bodies'
    size, = legacy_sizes(args.exe, public_fixture, (64,))
    print('generated bytes for 64 straight-line public functions:', size)
    # Includes bounded groups and compatibility aliases. Proof support performs
    # local elimination on demand instead of emitting every head theorem.
    assert size < 200_000, 'unused internal failure machinery is emitted'

    generated, = generated_outputs(args.exe, plan_fixture, (64,))
    size = len(generated)
    source = generated.decode()
    plan_names = re.findall(
        r'^def (.+?:eval:rule:\d+:plan)»?\s*:', source,
        flags=re.MULTILINE
    )
    print('default generated bytes/plans for 64 one-rule relations:',
          size, len(plan_names))
    assert len(plan_names) == 64, 'expected exactly one plan per source rule'
    assert len(set(plan_names)) == len(plan_names), 'duplicate rule plans emitted'
    assert size < 300_000, 'specialized evaluator flow was regenerated'
    for suffix in ('premises', 'recoverable', 'succeeds', 'failed', 'sound'):
        assert not re.search(
            rf'^(?:def|theorem) .+:eval:rule:\d+:{suffix}»?\s*:', source,
            flags=re.MULTILINE
        ), f'legacy specialized rule declaration remains: {suffix!r}'


if __name__ == '__main__':
    main()
